FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /
COPY ["graphweb.csproj", "."]
RUN dotnet restore "graphweb.csproj"
COPY . .
WORKDIR /
RUN dotnet build "graphweb.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "graphweb.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "graphweb.dll"]